apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: veerareddyravuri/appname:fb7948d7242bf2ad3abc8c5508204222d9e2e75a
          ports:
            - containerPort: 8080