apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: veerareddyravuri/appname:2add9b82e3dcd8b548106c9ea5f2ddb79d1cd990
          ports:
            - containerPort: 8080