apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: veerareddyravuri/appname:6d1a196e7b144a4392c485e56790d0ca8e5af834
          ports:
            - containerPort: 8080